[build]
  command = "npm install && npm run netlify-build"
  publish = ".next"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "18"
  NEXT_PUBLIC_BASE_PATH = ""

[[plugins]]
  package = "@netlify/plugin-nextjs"
  [plugins.inputs]
    # includeFiles = ["src/**/*"]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 